apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sn-pulsar-operator
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
  - repoURL: 'https://github.com/streamnative/charts.git'
    path: charts/pulsar-operator
    targetRevision: branch-pulsar-operator-0.16.3
    helm:
      valueFiles:
      - $values-repo/values/operator.yaml
  - repoURL: {{ .Values.values.repo.url }}
    targetRevision: {{ .Values.values.repo.revision }}
    ref: values-repo
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  syncPolicy:
    syncOptions:
    - Replace=true
    - CreateNamespace=true